spring:
  profiles:
    active: prod
  application:
    name: koces-receipt

logging:
  level:
    org:
      springframework: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.wqrzlfhhecugscdlyfhf
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 10000
      maximum-pool-size: 15
      minimum-idle: 1
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 11345

---
spring:
  config:
    activate:
      on-profile: dev, test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.wqrzlfhhecugscdlyfhf
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 10000
      maximum-pool-size: 15
      minimum-idle: 1
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 11345
---
spring:
  config:
    activate:
      on-profile: local
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/e-receipt
    username: allink-admin
    password: "devonshin120#$"
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 10000
      maximum-pool-size: 15
      minimum-idle: 1
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 11345

# production 실 운영 환경
---
spring:
  config:
    activate:
      on-profile: production
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 3
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none